# Generated by Django 5.1.4 on 2024-12-29 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Item",
            fields=[
                (
                    "item_id",
                    models.CharField(max_length=255, primary_key=True, serialize=False),
                ),
                ("item_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "listing_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("seller", models.CharField(blank=True, max_length=255, null=True)),
                ("msrp", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "listed_price",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("movement", models.CharField(blank=True, max_length=255, null=True)),
                ("brand", models.CharField(blank=True, max_length=255, null=True)),
                ("condition", models.CharField(blank=True, max_length=255, null=True)),
                ("department", models.CharField(blank=True, max_length=255, null=True)),
                ("sales", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
